print("""===Create your own hero!===""")
print("Let's create a hero and send them on a quick adventure!")
print()
name = input("What's their name? ")
height = input("How tall are they? ")
weapon = input("What kind of weapon do they use? ")
weather = input("Is the weather bright or stormy? ")
time = input("Is it day or night? ")
monster = input("Gimme a monster: ")
print(f"One {weather} {time}, {name} grabbed their {weapon} and took their {height} selves out for an adventure to slay a {monster}!")